export const caseStudies = [
  {
    title: "Risland India",
    summary: "Sales & Service Cloud Implementation for Real Estate",
    image: "/assets/images/Risland_India.png",
    goal: "To implement Salesforce Sales and Service Cloud to enhance customer experience, operational efficiency, and financial performance in the Real Estate industry.",
    implementation: [
      "Enquiry to Booking process implemented in Salesforce Platform.",
      "Created customer 360-degree view.",
      "Guided Booking creation and inventory blocking.",
      "Product setup for 3 locations with demographic variations.",
      "Automated business rules and approval processes.",
      "Finance integrations and automated booking orchestration.",
    ],
    technology: ["Salesforce"],
  },
  {
    title: "Hero Finance",
    summary: "CPQ Implementation involves deploying salesforce Configure, Price, Quote tools to automate product configuration, pricing, and quote generation and efficient sales processes.",
    image: "/assets/images/hero_finance.png",
    goal: "Streamlined pricing and quoting with a 40% reduction in quote generation time and 25% improvement in deal closures.",
    implementation: [
      "Automated quote generation and approvals.",
      "Multi-tiered discount management.",
      "CRM and customer data integration.",
      "Automated contract generation and renewals.",
      "Product catalog and pricing configuration.",
    ],
    technology: ["Salesforce CPQ"],
  },
  {
    title: "Region of Peel",
    summary: "Government Digitization is the use of digital technologies to streamline public services, improve efficiency, and enhance citizen engagement.",
    image: "/assets/images/RegionOFPeel-removebg-preview.png",
    goal: "Digitized operations for the Government of Canada, enabling citizens to file taxes and apply for services online.",
    implementation: [
      "Requirement analysis with user interviews.",
      "Intuitive system for increased productivity.",
      "Single repository with advanced analytics.",
      "Lightning Template for customer community.",
      "Classic to Lightning migration.",
      "Ongoing support at reduced costs.",
    ],
    technology: ["Salesforce Lightning", "Salesforce Classic", "Apex"],
  },
  {
    title: "BD",
    summary: "Project Management Gantt Chart is a visual project planning tool that displays tasks along a timeline, helping teams track progress, manage dependencies, and ensure timely completion of project milestones.",
    image: "/assets/images/bd.svg",
    goal: "Implemented a Gantt chart system for exhaustive project management using custom LWC.",
    implementation: [
      "Integrated with custom Gantt JS library.",
      "Developed custom Apex for Gantt features.",
      "Custom VF Page for Gantt chart display.",
    ],
    technology: ["Salesforce", "Visual Force", "JavaScript"],
  },
  {
    title: "Cloud Synapps",
    summary: "Dynamic Form System for Government refers to a digital solution that enables government agencies to create, manage, and customize interactive forms in real-time, allowing efficient data collection, automated processing, and improved citizen services through a user-friendly and adaptive interface.",
    image: "/assets/images/cloudSynaps-removebg-preview.png",
    goal: "Built a drag-and-drop form system with digital signatures for government use.",
    implementation: [
      "Classic to Lightning conversion.",
      "VisualForce to Lightning migration.",
      "Custom LEX components.",
      "Drag-and-drop UI for admins.",
      "Support for multiple forms and S-Objects.",
    ],
    technology: ["Salesforce", "Apex"],
  },
  {
    title: "CPQ Implementation",
    summary: "Streamlined Billing and Sales Processes** refer to the integration of automated tools and workflows that simplify quoting, invoicing, and revenue management—resulting in faster transactions, reduced errors, and improved customer satisfaction.",
    image: "/assets/images/Integrate-with-Salesforce-CPQ-removebg-preview.png",
    goal: "Reduced quote generation time by 30% and billing errors by 50% with automated CPQ processes.",
    implementation: [
      "Product bundling and flexible pricing.",
      "Automated quote generation.",
      "Discount and approval workflows.",
      "Usage-based billing.",
      "Revenue recognition automation.",
      "Contract and renewal management.",
    ],
    technology: ["Salesforce CPQ"],
  },
];
